/**
 * Chain brands to filter out - not date-worthy
 */
export const CHAIN_BLACKLIST = [
  'starbucks',
  'tim hortons',
  'mcdonalds',
  'subway',
  'taco bell',
  'pizza pizza',
  'second cup',
  'harveys',
  'wendys',
  'burger king',
  'kfc',
  'popeyes',
  'chipotle',
  'five guys',
  'freshii',
  'booster juice',
  'cobs bread',
  'earls',
  'joeys',
  'moxies',
  'milestones',
  'the keg',
  'montanas',
  'boston pizza',
  'swiss chalet',
  'mary browns',
  "a&w",
  'dairy queen',
  'baskin robbins',
  'gregorys',
  "pete's coffee",
  'dunkin',
] as const;
