/**
 * Places API (New) uses Table A place types.
 * @see https://developers.google.com/maps/documentation/places/web-service/place-types
 */

export const OFFICIAL_TYPES = [
  'restaurant',
  'cafe',
  'bar',
  'bakery',
  'ice_cream_shop',
  'coffee_shop',
  'wine_bar',
  'cocktail_bar',
  'dessert_shop',
  'chocolate_factory',
  'candy_store',
  'food_court',
  'night_club',
  'bar_and_grill',
  'pub',
  'comedy_club',
  'karaoke',
  'movie_theater',
  'bowling_alley',
  'amusement_park',
  'museum',
  'art_gallery',
  'performing_arts_theater',
  'concert_hall',
  'opera_house',
  'cultural_center',
  'book_store',
  'library',
  'historical_landmark',
  'park',
  'botanical_garden',
  'hiking_area',
  'beach',
  'marina',
  'observation_deck',
  'national_park',
  'garden',
  'wildlife_park',
  'spa',
  'yoga_studio',
  'art_studio',
  'brewery',
] as const;

/**
 * Keyword searches - only neighbourhoods within 3km of Bahen Centre.
 * Text Search uses locationBias with radius, but cleaner to keep list accurate.
 */
export const KEYWORD_SEARCHES = [
  'rooftop bar Toronto',
  'speakeasy cocktail bar Toronto',
  'whiskey bar Toronto',
  'champagne bar Toronto',
  'beer garden Toronto',
  'sake bar Toronto',
  'tiki bar Toronto',
  'natural wine bar Toronto',
  'omakase restaurant Toronto',
  'chefs table Toronto',
  'tasting menu Toronto',
  'underground supper club Toronto',
  'hidden restaurant Toronto',
  'farm to table Toronto',
  'fondue restaurant Toronto',
  'hot pot romantic Toronto',
  'all you can eat sushi Toronto',
  'izakaya Toronto',
  'live jazz bar Toronto',
  'piano bar Toronto',
  'live music venue Toronto',
  'comedy club Toronto',
  'open mic night Toronto',
  'burlesque show Toronto',
  'board game cafe Toronto',
  'cat cafe Toronto',
  'immersive art exhibit Toronto',
  'virtual reality experience Toronto',
  'pottery class date night Toronto',
  'painting class Toronto',
  'cocktail making class Toronto',
  'cooking class date Toronto',
  'chocolate making class Toronto',
  'flower arranging class Toronto',
  'axe throwing Toronto',
  'dance class couples Toronto',
  'salsa dancing Toronto',
  'rooftop patio Toronto',
  'waterfront walk Toronto',
  'secret garden Toronto',
  'graffiti alley Toronto',
  'night market Toronto',
  'independent cinema Toronto',
  'art house theater Toronto',
  'independent bookstore Toronto',
  'vintage clothing shop Toronto',
  'record store Toronto',
  'dessert bar Toronto',
  'crepe restaurant Toronto',
  'afternoon tea Toronto',
  'specialty coffee Toronto',
  'boba tea cafe Toronto',
  // Neighbourhoods within 3km of Bahen
  'Distillery District restaurant',
  'Kensington Market cafe hidden gem',
  'Queen West gallery bar',
  'Ossington bar restaurant',
  'Little Italy patio Toronto',
  'Harbourfront date activity',
  'Chinatown late night Toronto',
  'Little Portugal Toronto',
  'Annex restaurant Toronto',
  'Yorkville restaurant Toronto',
  'King West rooftop Toronto',
  'Roncesvalles date spot',
] as const;
